@hostname = http://122.172.87.185:8080

GET {{hostname}}/api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Accept: application/json

###
GET {{hostname}}/api/contacts/8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77
Accept: application/xml
###
GET {{hostname}}/api/contacts
Accept: application/json

###
GET {{hostname}}/api/contacts
Accept: application/xml

###
GET {{hostname}}/api/contacts/?gender=Female
Accept: application/json

###
GET {{hostname}}/api/contacts/?gender=Female
Accept: application/xml
###
GET {{hostname}}/api/contacts/?city=Atlanta
Accept: application/json

###
GET {{hostname}}/api/contacts/?city=Atlanta
Accept: application/xml
###
GET {{hostname}}/api/contacts/?state=Georgia
Accept: application/json

###
GET {{hostname}}/api/contacts/?state=Georgia
Accept: application/xml
###
GET {{hostname}}/api/contacts/?country=United+States
Accept: application/json

###
GET {{hostname}}/api/contacts/?country=United+States
Accept: application/xml

###
POST {{hostname}}/api/contacts
Accept: application/xml
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<contact>
  <id>8ddb7fcf-0a7a-4eeb-a78f-13238ed85a77</id>
  <firstname>Esme</firstname>
  <lastname>Filipyev</lastname>
  <gender>Male</gender>
  <email>efilipyev5c@rambler.ru</email>
  <phone>4042662103</phone>
  <address>9 Hermina Trail</address>
  <city>Atlanta</city>
  <state>Georgia</state>
  <country>United States</country>
  <pincode>31132</pincode>
</contact>

###
POST {{hostname}}/api/contacts
Accept: application/json
Content-Type: application/json

{
    "id": "95c41e9e-9b7e-429d-ba4e-5e2e1a44044b",
    "firstname": "Roy",
    "lastname": "Oldaker",
    "gender": "Male",
    "email": "roldakeru@scientificamerican.com",
    "phone": "5089917999",
    "address": "842 Hauk Trail",
    "city": "Worcester",
    "state": "Massachusetts",
    "country": "United States",
    "pincode": "01654"
}

###
POST {{hostname}}/api/contacts
Accept: application/json
Content-Type: application/json

{
    "firstname": "Vinod",
    "lastname": "Kumar",
    "gender": "Male",
    "email": "vinod@vinod.co",
    "phone": "9731424784",
    "address": "TF-1 Elegant Elite, 1st crs, 1st mn, ISRO layout",
    "city": "Bangalore",
    "state": "Karnataka",
    "country": "India",
    "pincode": "560078"
}

###
POST {{hostname}}/api/contacts
Accept: application/xml
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<contact>
  <firstname>Shyam</firstname>
  <lastname>Sundar</lastname>
  <gender>Male</gender>
  <email>shyam.sundar@xmpl.com</email>
  <phone>9876587654</phone>
  <address>SBI Layout</address>
  <city>Bangalore</city>
  <state>Karnataka</state>
  <country>India</country>
  <pincode>560098</pincode>
</contact>

###

GET {{hostname}}/api/contacts/a39be565-7bf3-4821-aa96-e592a8e8963d
Accept: application/json
###

GET {{hostname}}/api/contacts/a39be565-7bf3-4821-aa96-e592a8e8963d
Accept: application/xml
###
GET {{hostname}}/api/contacts?email=roldakeru@scientificamerican.com
Accept: application/xml
###
GET {{hostname}}/api/contacts?email=shyam.sundar@example.com
Accept: application/json

###
GET {{hostname}}/api/contacts?phone=4042662103
Accept: application/xml
###
GET {{hostname}}/api/contacts?phone=4042662103
Accept: application/json

###
PUT {{hostname}}/api/contacts/a39be565-7bf3-4821-aa96-e592a8e8963d
Accept: application/xml
Content-Type: application/xml

<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<contact>
  <firstname>Shyam</firstname>
  <lastname>Sundar</lastname>
  <gender>Male</gender>
  <email>shyam.sundar@example.com</email>
  <phone>9876587654</phone>
  <address>SBI Layout, Konanakunte</address>
  <city>Bangalore</city>
  <state>Karnataka</state>
  <country>India</country>
  <pincode>560098</pincode>
</contact>

###
GET {{hostname}}/api/contacts/a6251462-a701-4051-a154-fa419c668057
Accept: application/xml

###
DELETE {{hostname}}/api/contacts/84724a4b-7195-4a89-9589-ab538a235002
Accept: application/xml


